name: 🐞 Bug Report
description: When a feature is not behaving as expected.
labels: [bug]
body:
  - type: textarea
    id: Describe
    attributes:
      label: Describe the bug?
      description: A clear and concise description of what the bug is?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior. Use bulletpoints and keep them as simple as possible - any steps that are not necessary to reproduce the issue should be omited.
    validations:
      required: true
  - type: textarea
    id: reproduction-item
    attributes:
      label: Reproduction Item/World
      description: Please include a link to content that replicates this issue. This can be link to public folder/world (make sure it's marked public please or that world access is set to Anyone) or .ResonitePackage file uploaded directly here. If the issue cannot be replicated through an item/world, just type "N/A". 
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add media to help explain your problem
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Resonite Version Number
      placeholder: 1.2.3 (USE AN ACTUAL VERSION NUMBER)
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What Platforms does this occur on?
      multiple: true
      options:
        - "Windows"
        - "Linux"
        - "Android / Quest"
    validations:
      required: true
  - type: input
    id: headset
    attributes:
      label: What headset if any do you use?
      placeholder: Vive, Desktop?
  - type: textarea
    id: log-files
    attributes:
      label: Log Files
      description: Please provide a clean log file from replicating this issue.(**DO NOT USE MODS**. Start the client, replicate the issue and exit immediately.) Information on the different kinds of log files and where to find them can be found on our [wiki](https://wiki.resonite.com/Log_Files).
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: textarea
    id: reporters
    attributes:
      label: Reporters
      description: Usernames / Discord handles of anyone (including yourself) who has reported/replicated this bug (will be used to credit in release notes).
