name: Content Issue
description: For issues/feature requests relating to tutorial/home worlds, default facets, keyboards, video and audio players, and other content produced by our content team.
labels: [content]
assignees: AegisTheWolf, RyuviTheViali, RueShejn
body:
  - type: textarea
    id: Describe
    attributes:
      label: Describe the Underlying Issue
      description: For both feature requests, and bug reports, please provide a clear and description of what the issue is and the underlying problem you are trying to solve with the content.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Where is the issue found? Provide detail on the specific object/world/UI/other content item you are referring to, and where the issue lies.
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of how you believe the content should work.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Video
      description: Add media to help visually explain the content issue you are reporting.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: textarea
    id: reporters
    attributes:
      label: Reporters
      description: Usernames / Discord handles of anyone (including yourself) who has reported/replicated this bug (will be used to credit in release notes).
