name: Prerelease Feedback
description: Bug reports and feedback relating to prerelease builds of Resonite.
labels: prerelease
assignees: shiftyscales
body:
  - type: textarea
    id: Describe
    attributes:
      label: Describe the issue.
      description: A clear and concise description of what the issue is?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior. If relevant, please include a link to content that exhibits this issue via a public folder, or world. recreate the issue in a new grid space template, and edit the world's metadata to 'anyone'.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add media to help explain your problem
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Resonite Version Number
      placeholder: 1.2.3 (USE AN ACTUAL VERSION NUMBER)
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: What Platforms does this occur on?
      multiple: true
      options:
        - "Windows"
        - "Linux"
        - "Android / Quest"
    validations:
      required: true
  - type: input
    id: headset
    attributes:
      label: What headset if any do you use?
      placeholder: Vive, Desktop?
  - type: textarea
    id: log-files
    attributes:
      label: Log Files
      description: Please provide a clean log file from replicating this issue. **Please also ensure this issue only occurs on the prerelease build.** Information on the different kinds of log files and where to find them can be found on our [wiki](https://wiki.resonite.com/Log_Files).
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: textarea
    id: reporters
    attributes:
      label: Reporters
      description: Usernames / Discord handles of anyone (including yourself) who has reported/replicated this feedback (will be used to credit in release notes).
