name: Check bug reports for log files

on:
  issues:
    types: [labeled]

jobs:
  check-log:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Check if log file exists
        uses: Yellow-Dog-Man/logscanner-action@bd717cd37b5ee82719fbce2206b2a15d257abc20 # v1.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
