name: Check bug reports for log files

on:
  issues:
    types: [labeled]

jobs:
  check-log:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Check if log file exists
        uses: Yellow-Dog-Man/logscanner-action@3e881b720daba9899a4b252346eca6ded51ef4c8 # v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
