name: Check bug reports for log files

on:
  issues:
    types: [labeled]

jobs:
  check-log:
    if: github.event.label.name == 'bug' || github.event.label.name == 'prerelease'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Check if log file exists
        uses: Yellow-Dog-Man/logscanner-action@v1.2.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
